image: alpine/edge
packages: [ zola ]
oauth: pages.sr.ht/PAGES:RW
environment:
  site: xerexcoded.srht.site
sources:
  - https://git.sr.ht/~xerexcoded/xelog
tasks:
  - build: |
      cd xelog
      zola build
  - package: |
      cd xelog
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
