name: Deploy Zola Blog to Linode

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t xeera/zola-blog .
        docker push xeera/zola-blog

    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_IP }}
        username: ${{ secrets.LINODE_USERNAME }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        script: |
          docker pull xeera/zola-blog
          docker stop zola-blog || true
          docker rm zola-blog || true
          docker run -d --name zola-blog -p 8080:8080 xeera/zola-blog
